// A function is a block of code that performs a specific task.
// A Js function is executed when "something" invokes it(calls it).
// Invoke means calling a function

// Syntax of function
// e.g.
// function demo()
// {
// code goes here
// }

// demo() //invoking or calling a function

// e.g. function
// function greet(){
//     console.log("Hello Bro");
// }

// greet()

// Parameters and Arguments
// A function can be defined with set of parameters that it will take.
// Parameters are generally the values that we want the function to accept.
// Arguments are values that we pass for those parameters.

function sum(a,b){
    console.log(a+ b)
}
sum(4,5)